# Generated by Django 3.0.8 on 2020-07-30 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='enlisted_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='car',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='extraInfo',
            field=models.TextField(blank=True, null=True, verbose_name='Additional Information'),
        ),
        migrations.AlterField(
            model_name='car',
            name='flaws',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='rebuildingLink',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
