# Generated by Django 3.0.8 on 2020-07-30 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_auto_20200730_1040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carimages',
            name='date',
        ),
        migrations.RemoveField(
            model_name='repairedcarimages',
            name='date',
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='date',
        ),
    ]
